= Pdfs from Antora using pagedjs

This project adapts the principles behind asciidoctor-pdf.js to work in Antora.

* Slight tweaks to html generation.
* UI project adapted to pdf output based on pagedjs.
* pdf rendering through headless Chromium controlled through Puppeteer.
* content supplied to Chromium by running a local server.

Current output:

* One pdf per output html page.
* pdfs are added to the `_attachments` directory in the component, in the same directory structure as the pages.

== How to set this up

=== Antora

You need a local copy of Antora with several MRs applied.

* link:https://gitlab.com/antora/antora/merge_requests/423[Upgrade to Asciidoctor.js 2.0.x]
* link:https://gitlab.com/antora/antora/merge_requests/440[Allow a custom converter to replace/override the default HTML5 converter]
* link:https://gitlab.com/antora/antora/merge_requests/439[Allow the pipeline to explicitly add extensions (and converters/templates) to the asciidoc config]
* A fix for link:https://gitlab.com/antora/antora/issues/552[cli should allow specifying UI start_path as well as the UI bundle itself]

The plausible way to get this is by cloning my link:https://gitlab.com/djencks/antora[Antora fork] and checking out the `issue-522-347-548-asciidoctor-2-delegating-converters-explicit-converters` branch.

Run yarn to set up the node_modules monorepo in antora.

=== This project, asciidoctor-pdf.js, antora branch

After you've cloned (from my fork) and switched to this branch, run yarn to set up the monorepo here.

Now you have to link the local patched Antora into this project.

Find your @antora in the antora monorepo, say `/Users/david/projects/antora/antora/node_modules/@antora`

Remove or move your `node_modules/@antora` in this project.

Symlink to the local antora: `ln -s /Users/david/projects/antora/antora/node_modules/@antora node_modules/\@antora`

BEWARE! 
Whenever you run `yarn` here, you'll need to run `yarn` in antora!
`yarn` here follows the symlink and installs the released version of antora into antora's node_modules.
Better, move `node_modules/@antora` out of the way before running yarn, and back afterwards.

== Set up a way to run your local copy of antora

in e.g. `~/.profile`, `export ANTORA_DEV=~/projects/antora/antora/node_modules/.bin/antora`

== UI

Get the `pdf-with-hbs` `antora-ui-default` branch from link:https://gitlab.com/djencks/antora-ui-default[my fork] and build it.
You'll need the path to it for your playbook or command line.

== (Optional) Set up your playbook if you want a simpler command line

----
ui:
  bundle:
    url: ./../../../antora-ui-default/build/ui-pdf-bundle.zip
    snapshot: true
    start_path: pdf
----

== Running

A typical command line in this directory, specifying both UI bundle and start_path:
----
 $ANTORA_DEV ../../antora/simple-examples/multiple-components/xrefs/antora-playbook.yml  --stacktrace --generator ./node_modules/\@antora-pdf/pdf-generator  --ui-bundle-url ../../antora/antora-ui-default/build/ui-pdf-bundle.zip --ui-start-path pdf
----

The pipeline module must be referred to with a local file path.

== Configuration

By default, all published pages are converted to pdf and put in each components `_attachments` directory.

Alternatively, you can list the files to convert in each component descriptor under the pdfFiles key, in the form `<module>:<relative>`.

----
pdfFiles:
- ROOT:_sitepdf.adoc
----

If this file is hidden (by the initial `\_`) it will be published anyway, with the initial `_` removed from the pdf name.

For instance, you can take a nav.adoc file and convert the `* \xref::` to `include::`.
Be sure to include e.g. `[lineoffset=1]`, where the lineoffset is most likely the number of `*` at the beginning of the line.

== Html "Preview"

The html that gets printed is written out in the normal spots in the site.
By commenting out a couple lines in converter.js you can see the same thing Chromium does at `http://localhost:8081`

== Next steps

?

It's presumably possible to automatically convert nav.adoc files to "`including files`", but I'd like to see some real world experience with manual conversions before trying to implement this.
